// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SITHEC.Infrastructure.Contexts;

namespace SITHEC.Infrastructure.Migrations
{
    [DbContext(typeof(SITHECDbContext))]
    [Migration("20220422183542_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SITHEC.Application.Entities.EntHumano", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Altura")
                        .HasColumnType("int");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Peso")
                        .HasColumnType("float");

                    b.Property<bool>("Sexo")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Humanos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Altura = 168,
                            Edad = 29,
                            Nombre = "Diego",
                            Peso = 95.0,
                            Sexo = false
                        },
                        new
                        {
                            Id = 2,
                            Altura = 175,
                            Edad = 25,
                            Nombre = "Ronaldo",
                            Peso = 98.5,
                            Sexo = false
                        },
                        new
                        {
                            Id = 3,
                            Altura = 165,
                            Edad = 33,
                            Nombre = "Danai",
                            Peso = 60.0,
                            Sexo = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
